-- +goose Up
CREATE TABLE IF NOT EXISTS movements (
  id SERIAL PRIMARY KEY,
  type VARCHAR(50) NOT NULL,
  amount NUMERIC(12,2) NOT NULL,
  category VARCHAR(100) NOT NULL,
  description TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS limits (
  id SERIAL PRIMARY KEY,
  category VARCHAR(100) NOT NULL,
  value NUMERIC(12,2) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- +goose Down
DROP TABLE IF EXISTS limits;
DROP TABLE IF EXISTS movements;
