-- +goose Up
ALTER TABLE users ALTER COLUMN id SET DEFAULT uuidv7();
ALTER TABLE incomes ALTER COLUMN id SET DEFAULT uuidv7();
ALTER TABLE debts ALTER COLUMN id SET DEFAULT uuidv7();
ALTER TABLE movements ALTER COLUMN id SET DEFAULT uuidv7();
ALTER TABLE limits ALTER COLUMN id SET DEFAULT uuidv7();

-- +goose Down
ALTER TABLE users ALTER COLUMN id DROP DEFAULT;
ALTER TABLE incomes ALTER COLUMN id DROP DEFAULT;
ALTER TABLE debts ALTER COLUMN id DROP DEFAULT;
ALTER TABLE movements ALTER COLUMN id DROP DEFAULT;
ALTER TABLE limits ALTER COLUMN id DROP DEFAULT;
