CREATE TABLE IF NOT EXISTS movimientos (
  id SERIAL PRIMARY KEY,
  tipo VARCHAR(50) NOT NULL,
  monto NUMERIC(12,2) NOT NULL,
  categoria VARCHAR(100) NOT NULL,
  descripcion TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS limites (
  id SERIAL PRIMARY KEY,
  categoria VARCHAR(100) NOT NULL,
  valor NUMERIC(12,2) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
