// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: financialadvisor/finance/v1/finance.proto

package financev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Movement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Movement) Reset() {
	*x = Movement{}
	mi := &file_financialadvisor_finance_v1_finance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Movement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Movement) ProtoMessage() {}

func (x *Movement) ProtoReflect() protoreflect.Message {
	mi := &file_financialadvisor_finance_v1_finance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Movement.ProtoReflect.Descriptor instead.
func (*Movement) Descriptor() ([]byte, []int) {
	return file_financialadvisor_finance_v1_finance_proto_rawDescGZIP(), []int{0}
}

func (x *Movement) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Movement) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Movement) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Movement) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Movement) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type RegisterMovementsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movement      *Movement              `protobuf:"bytes,1,opt,name=movement,proto3" json:"movement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterMovementsRequest) Reset() {
	*x = RegisterMovementsRequest{}
	mi := &file_financialadvisor_finance_v1_finance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterMovementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMovementsRequest) ProtoMessage() {}

func (x *RegisterMovementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_financialadvisor_finance_v1_finance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMovementsRequest.ProtoReflect.Descriptor instead.
func (*RegisterMovementsRequest) Descriptor() ([]byte, []int) {
	return file_financialadvisor_finance_v1_finance_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterMovementsRequest) GetMovement() *Movement {
	if x != nil {
		return x.Movement
	}
	return nil
}

type RegisterMovementsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movement      *Movement              `protobuf:"bytes,1,opt,name=movement,proto3" json:"movement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterMovementsResponse) Reset() {
	*x = RegisterMovementsResponse{}
	mi := &file_financialadvisor_finance_v1_finance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterMovementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMovementsResponse) ProtoMessage() {}

func (x *RegisterMovementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_financialadvisor_finance_v1_finance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMovementsResponse.ProtoReflect.Descriptor instead.
func (*RegisterMovementsResponse) Descriptor() ([]byte, []int) {
	return file_financialadvisor_finance_v1_finance_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterMovementsResponse) GetMovement() *Movement {
	if x != nil {
		return x.Movement
	}
	return nil
}

var File_financialadvisor_finance_v1_finance_proto protoreflect.FileDescriptor

const file_financialadvisor_finance_v1_finance_proto_rawDesc = "" +
	"\n" +
	")financialadvisor/finance/v1/finance.proto\x12\x1bfinancialadvisor.finance.v1\"\x84\x01\n" +
	"\bMovement\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"]\n" +
	"\x18RegisterMovementsRequest\x12A\n" +
	"\bmovement\x18\x01 \x01(\v2%.financialadvisor.finance.v1.MovementR\bmovement\"^\n" +
	"\x19RegisterMovementsResponse\x12A\n" +
	"\bmovement\x18\x01 \x01(\v2%.financialadvisor.finance.v1.MovementR\bmovement2\x95\x01\n" +
	"\x0eFinanceService\x12\x82\x01\n" +
	"\x11RegisterMovements\x125.financialadvisor.finance.v1.RegisterMovementsRequest\x1a6.financialadvisor.finance.v1.RegisterMovementsResponseBAZ?financialAdvisor/services/core/internal/pb/finance/v1;financev1b\x06proto3"

var (
	file_financialadvisor_finance_v1_finance_proto_rawDescOnce sync.Once
	file_financialadvisor_finance_v1_finance_proto_rawDescData []byte
)

func file_financialadvisor_finance_v1_finance_proto_rawDescGZIP() []byte {
	file_financialadvisor_finance_v1_finance_proto_rawDescOnce.Do(func() {
		file_financialadvisor_finance_v1_finance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_financialadvisor_finance_v1_finance_proto_rawDesc), len(file_financialadvisor_finance_v1_finance_proto_rawDesc)))
	})
	return file_financialadvisor_finance_v1_finance_proto_rawDescData
}

var file_financialadvisor_finance_v1_finance_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_financialadvisor_finance_v1_finance_proto_goTypes = []any{
	(*Movement)(nil),                  // 0: financialadvisor.finance.v1.Movement
	(*RegisterMovementsRequest)(nil),  // 1: financialadvisor.finance.v1.RegisterMovementsRequest
	(*RegisterMovementsResponse)(nil), // 2: financialadvisor.finance.v1.RegisterMovementsResponse
}
var file_financialadvisor_finance_v1_finance_proto_depIdxs = []int32{
	0, // 0: financialadvisor.finance.v1.RegisterMovementsRequest.movement:type_name -> financialadvisor.finance.v1.Movement
	0, // 1: financialadvisor.finance.v1.RegisterMovementsResponse.movement:type_name -> financialadvisor.finance.v1.Movement
	1, // 2: financialadvisor.finance.v1.FinanceService.RegisterMovements:input_type -> financialadvisor.finance.v1.RegisterMovementsRequest
	2, // 3: financialadvisor.finance.v1.FinanceService.RegisterMovements:output_type -> financialadvisor.finance.v1.RegisterMovementsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_financialadvisor_finance_v1_finance_proto_init() }
func file_financialadvisor_finance_v1_finance_proto_init() {
	if File_financialadvisor_finance_v1_finance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_financialadvisor_finance_v1_finance_proto_rawDesc), len(file_financialadvisor_finance_v1_finance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_financialadvisor_finance_v1_finance_proto_goTypes,
		DependencyIndexes: file_financialadvisor_finance_v1_finance_proto_depIdxs,
		MessageInfos:      file_financialadvisor_finance_v1_finance_proto_msgTypes,
	}.Build()
	File_financialadvisor_finance_v1_finance_proto = out.File
	file_financialadvisor_finance_v1_finance_proto_goTypes = nil
	file_financialadvisor_finance_v1_finance_proto_depIdxs = nil
}
