// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: financialadvisor/advisor/v1/advisor.proto

package advisorv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdvisorService_CalculateTax_FullMethodName    = "/financialadvisor.advisor.v1.AdvisorService/CalculateTax"
	AdvisorService_RegisterIncomes_FullMethodName = "/financialadvisor.advisor.v1.AdvisorService/RegisterIncomes"
	AdvisorService_RegisterDebts_FullMethodName   = "/financialadvisor.advisor.v1.AdvisorService/RegisterDebts"
)

// AdvisorServiceClient is the client API for AdvisorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdvisorServiceClient interface {
	CalculateTax(ctx context.Context, in *CalculateTaxRequest, opts ...grpc.CallOption) (*CalculateTaxResponse, error)
	RegisterIncomes(ctx context.Context, in *RegisterIncomesRequest, opts ...grpc.CallOption) (*RegisterIncomesResponse, error)
	RegisterDebts(ctx context.Context, in *RegisterDebtsRequest, opts ...grpc.CallOption) (*RegisterDebtsResponse, error)
}

type advisorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdvisorServiceClient(cc grpc.ClientConnInterface) AdvisorServiceClient {
	return &advisorServiceClient{cc}
}

func (c *advisorServiceClient) CalculateTax(ctx context.Context, in *CalculateTaxRequest, opts ...grpc.CallOption) (*CalculateTaxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateTaxResponse)
	err := c.cc.Invoke(ctx, AdvisorService_CalculateTax_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *advisorServiceClient) RegisterIncomes(ctx context.Context, in *RegisterIncomesRequest, opts ...grpc.CallOption) (*RegisterIncomesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterIncomesResponse)
	err := c.cc.Invoke(ctx, AdvisorService_RegisterIncomes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *advisorServiceClient) RegisterDebts(ctx context.Context, in *RegisterDebtsRequest, opts ...grpc.CallOption) (*RegisterDebtsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterDebtsResponse)
	err := c.cc.Invoke(ctx, AdvisorService_RegisterDebts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdvisorServiceServer is the server API for AdvisorService service.
// All implementations must embed UnimplementedAdvisorServiceServer
// for forward compatibility.
type AdvisorServiceServer interface {
	CalculateTax(context.Context, *CalculateTaxRequest) (*CalculateTaxResponse, error)
	RegisterIncomes(context.Context, *RegisterIncomesRequest) (*RegisterIncomesResponse, error)
	RegisterDebts(context.Context, *RegisterDebtsRequest) (*RegisterDebtsResponse, error)
	mustEmbedUnimplementedAdvisorServiceServer()
}

// UnimplementedAdvisorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdvisorServiceServer struct{}

func (UnimplementedAdvisorServiceServer) CalculateTax(context.Context, *CalculateTaxRequest) (*CalculateTaxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateTax not implemented")
}
func (UnimplementedAdvisorServiceServer) RegisterIncomes(context.Context, *RegisterIncomesRequest) (*RegisterIncomesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterIncomes not implemented")
}
func (UnimplementedAdvisorServiceServer) RegisterDebts(context.Context, *RegisterDebtsRequest) (*RegisterDebtsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterDebts not implemented")
}
func (UnimplementedAdvisorServiceServer) mustEmbedUnimplementedAdvisorServiceServer() {}
func (UnimplementedAdvisorServiceServer) testEmbeddedByValue()                        {}

// UnsafeAdvisorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdvisorServiceServer will
// result in compilation errors.
type UnsafeAdvisorServiceServer interface {
	mustEmbedUnimplementedAdvisorServiceServer()
}

func RegisterAdvisorServiceServer(s grpc.ServiceRegistrar, srv AdvisorServiceServer) {
	// If the following call panics, it indicates UnimplementedAdvisorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdvisorService_ServiceDesc, srv)
}

func _AdvisorService_CalculateTax_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateTaxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdvisorServiceServer).CalculateTax(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdvisorService_CalculateTax_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdvisorServiceServer).CalculateTax(ctx, req.(*CalculateTaxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdvisorService_RegisterIncomes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterIncomesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdvisorServiceServer).RegisterIncomes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdvisorService_RegisterIncomes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdvisorServiceServer).RegisterIncomes(ctx, req.(*RegisterIncomesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdvisorService_RegisterDebts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDebtsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdvisorServiceServer).RegisterDebts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdvisorService_RegisterDebts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdvisorServiceServer).RegisterDebts(ctx, req.(*RegisterDebtsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdvisorService_ServiceDesc is the grpc.ServiceDesc for AdvisorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdvisorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "financialadvisor.advisor.v1.AdvisorService",
	HandlerType: (*AdvisorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateTax",
			Handler:    _AdvisorService_CalculateTax_Handler,
		},
		{
			MethodName: "RegisterIncomes",
			Handler:    _AdvisorService_RegisterIncomes_Handler,
		},
		{
			MethodName: "RegisterDebts",
			Handler:    _AdvisorService_RegisterDebts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "financialadvisor/advisor/v1/advisor.proto",
}
