// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: financialadvisor/advisor/v1/advisor.proto

package advisorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalculateTaxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdvisorId     string                 `protobuf:"bytes,1,opt,name=advisor_id,json=advisorId,proto3" json:"advisor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateTaxRequest) Reset() {
	*x = CalculateTaxRequest{}
	mi := &file_financialadvisor_advisor_v1_advisor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateTaxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateTaxRequest) ProtoMessage() {}

func (x *CalculateTaxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_financialadvisor_advisor_v1_advisor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateTaxRequest.ProtoReflect.Descriptor instead.
func (*CalculateTaxRequest) Descriptor() ([]byte, []int) {
	return file_financialadvisor_advisor_v1_advisor_proto_rawDescGZIP(), []int{0}
}

func (x *CalculateTaxRequest) GetAdvisorId() string {
	if x != nil {
		return x.AdvisorId
	}
	return ""
}

type CalculateTaxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tax           float64                `protobuf:"fixed64,1,opt,name=tax,proto3" json:"tax,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateTaxResponse) Reset() {
	*x = CalculateTaxResponse{}
	mi := &file_financialadvisor_advisor_v1_advisor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateTaxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateTaxResponse) ProtoMessage() {}

func (x *CalculateTaxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_financialadvisor_advisor_v1_advisor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateTaxResponse.ProtoReflect.Descriptor instead.
func (*CalculateTaxResponse) Descriptor() ([]byte, []int) {
	return file_financialadvisor_advisor_v1_advisor_proto_rawDescGZIP(), []int{1}
}

func (x *CalculateTaxResponse) GetTax() float64 {
	if x != nil {
		return x.Tax
	}
	return 0
}

type Income struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Date          string                 `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Income) Reset() {
	*x = Income{}
	mi := &file_financialadvisor_advisor_v1_advisor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Income) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Income) ProtoMessage() {}

func (x *Income) ProtoReflect() protoreflect.Message {
	mi := &file_financialadvisor_advisor_v1_advisor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Income.ProtoReflect.Descriptor instead.
func (*Income) Descriptor() ([]byte, []int) {
	return file_financialadvisor_advisor_v1_advisor_proto_rawDescGZIP(), []int{2}
}

func (x *Income) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Income) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Income) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Income) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type Debt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Creditor      string                 `protobuf:"bytes,2,opt,name=creditor,proto3" json:"creditor,omitempty"`
	Balance       float64                `protobuf:"fixed64,3,opt,name=balance,proto3" json:"balance,omitempty"`
	Installment   float64                `protobuf:"fixed64,4,opt,name=installment,proto3" json:"installment,omitempty"`
	DueDate       string                 `protobuf:"bytes,5,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Debt) Reset() {
	*x = Debt{}
	mi := &file_financialadvisor_advisor_v1_advisor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Debt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Debt) ProtoMessage() {}

func (x *Debt) ProtoReflect() protoreflect.Message {
	mi := &file_financialadvisor_advisor_v1_advisor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Debt.ProtoReflect.Descriptor instead.
func (*Debt) Descriptor() ([]byte, []int) {
	return file_financialadvisor_advisor_v1_advisor_proto_rawDescGZIP(), []int{3}
}

func (x *Debt) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Debt) GetCreditor() string {
	if x != nil {
		return x.Creditor
	}
	return ""
}

func (x *Debt) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *Debt) GetInstallment() float64 {
	if x != nil {
		return x.Installment
	}
	return 0
}

func (x *Debt) GetDueDate() string {
	if x != nil {
		return x.DueDate
	}
	return ""
}

type RegisterIncomesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdvisorId     string                 `protobuf:"bytes,1,opt,name=advisor_id,json=advisorId,proto3" json:"advisor_id,omitempty"`
	Incomes       []*Income              `protobuf:"bytes,2,rep,name=incomes,proto3" json:"incomes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterIncomesRequest) Reset() {
	*x = RegisterIncomesRequest{}
	mi := &file_financialadvisor_advisor_v1_advisor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterIncomesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterIncomesRequest) ProtoMessage() {}

func (x *RegisterIncomesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_financialadvisor_advisor_v1_advisor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterIncomesRequest.ProtoReflect.Descriptor instead.
func (*RegisterIncomesRequest) Descriptor() ([]byte, []int) {
	return file_financialadvisor_advisor_v1_advisor_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterIncomesRequest) GetAdvisorId() string {
	if x != nil {
		return x.AdvisorId
	}
	return ""
}

func (x *RegisterIncomesRequest) GetIncomes() []*Income {
	if x != nil {
		return x.Incomes
	}
	return nil
}

type RegisterIncomesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Incomes       []*Income              `protobuf:"bytes,1,rep,name=incomes,proto3" json:"incomes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterIncomesResponse) Reset() {
	*x = RegisterIncomesResponse{}
	mi := &file_financialadvisor_advisor_v1_advisor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterIncomesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterIncomesResponse) ProtoMessage() {}

func (x *RegisterIncomesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_financialadvisor_advisor_v1_advisor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterIncomesResponse.ProtoReflect.Descriptor instead.
func (*RegisterIncomesResponse) Descriptor() ([]byte, []int) {
	return file_financialadvisor_advisor_v1_advisor_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterIncomesResponse) GetIncomes() []*Income {
	if x != nil {
		return x.Incomes
	}
	return nil
}

type RegisterDebtsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdvisorId     string                 `protobuf:"bytes,1,opt,name=advisor_id,json=advisorId,proto3" json:"advisor_id,omitempty"`
	Debts         []*Debt                `protobuf:"bytes,2,rep,name=debts,proto3" json:"debts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDebtsRequest) Reset() {
	*x = RegisterDebtsRequest{}
	mi := &file_financialadvisor_advisor_v1_advisor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDebtsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDebtsRequest) ProtoMessage() {}

func (x *RegisterDebtsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_financialadvisor_advisor_v1_advisor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDebtsRequest.ProtoReflect.Descriptor instead.
func (*RegisterDebtsRequest) Descriptor() ([]byte, []int) {
	return file_financialadvisor_advisor_v1_advisor_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterDebtsRequest) GetAdvisorId() string {
	if x != nil {
		return x.AdvisorId
	}
	return ""
}

func (x *RegisterDebtsRequest) GetDebts() []*Debt {
	if x != nil {
		return x.Debts
	}
	return nil
}

type RegisterDebtsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Debts         []*Debt                `protobuf:"bytes,1,rep,name=debts,proto3" json:"debts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDebtsResponse) Reset() {
	*x = RegisterDebtsResponse{}
	mi := &file_financialadvisor_advisor_v1_advisor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDebtsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDebtsResponse) ProtoMessage() {}

func (x *RegisterDebtsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_financialadvisor_advisor_v1_advisor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDebtsResponse.ProtoReflect.Descriptor instead.
func (*RegisterDebtsResponse) Descriptor() ([]byte, []int) {
	return file_financialadvisor_advisor_v1_advisor_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterDebtsResponse) GetDebts() []*Debt {
	if x != nil {
		return x.Debts
	}
	return nil
}

type RegisterExpenseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdvisorId     string                 `protobuf:"bytes,1,opt,name=advisor_id,json=advisorId,proto3" json:"advisor_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterExpenseRequest) Reset() {
	*x = RegisterExpenseRequest{}
	mi := &file_financialadvisor_advisor_v1_advisor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterExpenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterExpenseRequest) ProtoMessage() {}

func (x *RegisterExpenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_financialadvisor_advisor_v1_advisor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterExpenseRequest.ProtoReflect.Descriptor instead.
func (*RegisterExpenseRequest) Descriptor() ([]byte, []int) {
	return file_financialadvisor_advisor_v1_advisor_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterExpenseRequest) GetAdvisorId() string {
	if x != nil {
		return x.AdvisorId
	}
	return ""
}

func (x *RegisterExpenseRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RegisterExpenseRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type RegisterExpenseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultExpense float64                `protobuf:"fixed64,1,opt,name=result_expense,json=resultExpense,proto3" json:"result_expense,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterExpenseResponse) Reset() {
	*x = RegisterExpenseResponse{}
	mi := &file_financialadvisor_advisor_v1_advisor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterExpenseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterExpenseResponse) ProtoMessage() {}

func (x *RegisterExpenseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_financialadvisor_advisor_v1_advisor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterExpenseResponse.ProtoReflect.Descriptor instead.
func (*RegisterExpenseResponse) Descriptor() ([]byte, []int) {
	return file_financialadvisor_advisor_v1_advisor_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterExpenseResponse) GetResultExpense() float64 {
	if x != nil {
		return x.ResultExpense
	}
	return 0
}

var File_financialadvisor_advisor_v1_advisor_proto protoreflect.FileDescriptor

const file_financialadvisor_advisor_v1_advisor_proto_rawDesc = "" +
	"\n" +
	")financialadvisor/advisor/v1/advisor.proto\x12\x1bfinancialadvisor.advisor.v1\"4\n" +
	"\x13CalculateTaxRequest\x12\x1d\n" +
	"\n" +
	"advisor_id\x18\x01 \x01(\tR\tadvisorId\"(\n" +
	"\x14CalculateTaxResponse\x12\x10\n" +
	"\x03tax\x18\x01 \x01(\x01R\x03tax\"X\n" +
	"\x06Income\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04date\x18\x04 \x01(\tR\x04date\"\x89\x01\n" +
	"\x04Debt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bcreditor\x18\x02 \x01(\tR\bcreditor\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x01R\abalance\x12 \n" +
	"\vinstallment\x18\x04 \x01(\x01R\vinstallment\x12\x19\n" +
	"\bdue_date\x18\x05 \x01(\tR\adueDate\"v\n" +
	"\x16RegisterIncomesRequest\x12\x1d\n" +
	"\n" +
	"advisor_id\x18\x01 \x01(\tR\tadvisorId\x12=\n" +
	"\aincomes\x18\x02 \x03(\v2#.financialadvisor.advisor.v1.IncomeR\aincomes\"X\n" +
	"\x17RegisterIncomesResponse\x12=\n" +
	"\aincomes\x18\x01 \x03(\v2#.financialadvisor.advisor.v1.IncomeR\aincomes\"n\n" +
	"\x14RegisterDebtsRequest\x12\x1d\n" +
	"\n" +
	"advisor_id\x18\x01 \x01(\tR\tadvisorId\x127\n" +
	"\x05debts\x18\x02 \x03(\v2!.financialadvisor.advisor.v1.DebtR\x05debts\"P\n" +
	"\x15RegisterDebtsResponse\x127\n" +
	"\x05debts\x18\x01 \x03(\v2!.financialadvisor.advisor.v1.DebtR\x05debts\"k\n" +
	"\x16RegisterExpenseRequest\x12\x1d\n" +
	"\n" +
	"advisor_id\x18\x01 \x01(\tR\tadvisorId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\"@\n" +
	"\x17RegisterExpenseResponse\x12%\n" +
	"\x0eresult_expense\x18\x01 \x01(\x01R\rresultExpense2\xfb\x02\n" +
	"\x0eAdvisorService\x12s\n" +
	"\fCalculateTax\x120.financialadvisor.advisor.v1.CalculateTaxRequest\x1a1.financialadvisor.advisor.v1.CalculateTaxResponse\x12|\n" +
	"\x0fRegisterIncomes\x123.financialadvisor.advisor.v1.RegisterIncomesRequest\x1a4.financialadvisor.advisor.v1.RegisterIncomesResponse\x12v\n" +
	"\rRegisterDebts\x121.financialadvisor.advisor.v1.RegisterDebtsRequest\x1a2.financialadvisor.advisor.v1.RegisterDebtsResponseBAZ?financialAdvisor/services/core/internal/pb/advisor/v1;advisorv1b\x06proto3"

var (
	file_financialadvisor_advisor_v1_advisor_proto_rawDescOnce sync.Once
	file_financialadvisor_advisor_v1_advisor_proto_rawDescData []byte
)

func file_financialadvisor_advisor_v1_advisor_proto_rawDescGZIP() []byte {
	file_financialadvisor_advisor_v1_advisor_proto_rawDescOnce.Do(func() {
		file_financialadvisor_advisor_v1_advisor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_financialadvisor_advisor_v1_advisor_proto_rawDesc), len(file_financialadvisor_advisor_v1_advisor_proto_rawDesc)))
	})
	return file_financialadvisor_advisor_v1_advisor_proto_rawDescData
}

var file_financialadvisor_advisor_v1_advisor_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_financialadvisor_advisor_v1_advisor_proto_goTypes = []any{
	(*CalculateTaxRequest)(nil),     // 0: financialadvisor.advisor.v1.CalculateTaxRequest
	(*CalculateTaxResponse)(nil),    // 1: financialadvisor.advisor.v1.CalculateTaxResponse
	(*Income)(nil),                  // 2: financialadvisor.advisor.v1.Income
	(*Debt)(nil),                    // 3: financialadvisor.advisor.v1.Debt
	(*RegisterIncomesRequest)(nil),  // 4: financialadvisor.advisor.v1.RegisterIncomesRequest
	(*RegisterIncomesResponse)(nil), // 5: financialadvisor.advisor.v1.RegisterIncomesResponse
	(*RegisterDebtsRequest)(nil),    // 6: financialadvisor.advisor.v1.RegisterDebtsRequest
	(*RegisterDebtsResponse)(nil),   // 7: financialadvisor.advisor.v1.RegisterDebtsResponse
	(*RegisterExpenseRequest)(nil),  // 8: financialadvisor.advisor.v1.RegisterExpenseRequest
	(*RegisterExpenseResponse)(nil), // 9: financialadvisor.advisor.v1.RegisterExpenseResponse
}
var file_financialadvisor_advisor_v1_advisor_proto_depIdxs = []int32{
	2, // 0: financialadvisor.advisor.v1.RegisterIncomesRequest.incomes:type_name -> financialadvisor.advisor.v1.Income
	2, // 1: financialadvisor.advisor.v1.RegisterIncomesResponse.incomes:type_name -> financialadvisor.advisor.v1.Income
	3, // 2: financialadvisor.advisor.v1.RegisterDebtsRequest.debts:type_name -> financialadvisor.advisor.v1.Debt
	3, // 3: financialadvisor.advisor.v1.RegisterDebtsResponse.debts:type_name -> financialadvisor.advisor.v1.Debt
	0, // 4: financialadvisor.advisor.v1.AdvisorService.CalculateTax:input_type -> financialadvisor.advisor.v1.CalculateTaxRequest
	4, // 5: financialadvisor.advisor.v1.AdvisorService.RegisterIncomes:input_type -> financialadvisor.advisor.v1.RegisterIncomesRequest
	6, // 6: financialadvisor.advisor.v1.AdvisorService.RegisterDebts:input_type -> financialadvisor.advisor.v1.RegisterDebtsRequest
	1, // 7: financialadvisor.advisor.v1.AdvisorService.CalculateTax:output_type -> financialadvisor.advisor.v1.CalculateTaxResponse
	5, // 8: financialadvisor.advisor.v1.AdvisorService.RegisterIncomes:output_type -> financialadvisor.advisor.v1.RegisterIncomesResponse
	7, // 9: financialadvisor.advisor.v1.AdvisorService.RegisterDebts:output_type -> financialadvisor.advisor.v1.RegisterDebtsResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_financialadvisor_advisor_v1_advisor_proto_init() }
func file_financialadvisor_advisor_v1_advisor_proto_init() {
	if File_financialadvisor_advisor_v1_advisor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_financialadvisor_advisor_v1_advisor_proto_rawDesc), len(file_financialadvisor_advisor_v1_advisor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_financialadvisor_advisor_v1_advisor_proto_goTypes,
		DependencyIndexes: file_financialadvisor_advisor_v1_advisor_proto_depIdxs,
		MessageInfos:      file_financialadvisor_advisor_v1_advisor_proto_msgTypes,
	}.Build()
	File_financialadvisor_advisor_v1_advisor_proto = out.File
	file_financialadvisor_advisor_v1_advisor_proto_goTypes = nil
	file_financialadvisor_advisor_v1_advisor_proto_depIdxs = nil
}
